# Generated by Django 3.2.4 on 2021-07-23 08:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Newbie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='il',
            new_name='ct',
        ),
        migrations.RemoveField(
            model_name='details',
            name='sp',
        ),
        migrations.AddField(
            model_name='allcourses',
            name='startedfrom',
            field=models.DateField(default=datetime.datetime(2021, 7, 23, 8, 37, 43, 675558, tzinfo=utc), verbose_name='started From'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='Your_choice',
            field=models.BooleanField(default=False),
        ),
    ]
