# Generated by Django 3.2.4 on 2021-07-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newbie', '0002_auto_20210723_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcourses',
            name='startedfrom',
            field=models.DateTimeField(verbose_name='started From'),
        ),
    ]
