# Generated by Django 3.2.4 on 2021-07-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Newbie', '0003_alter_allcourses_startedfrom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcourses',
            name='startedfrom',
        ),
    ]
